//
#pragma once

//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//
// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
//
//  DO NOT EDIT this file to adjust your configuration.  Create your own
//  APM_Config.h and use APM_Config.h.example as a reference.
//
// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
///
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
//
// Default and automatic configuration details.
//
// Notes for maintainers:
//
// - Try to keep this file organised in the same order as APM_Config.h.example
//
#include "defines.h"

///
/// DO NOT EDIT THIS INCLUDE - if you want to make a local change, make that
/// change in your local copy of APM_Config.h.
///
#include "APM_Config.h"
#include <AP_ADSB/AP_ADSB_config.h>
#include <AP_Follow/AP_Follow_config.h>
#include <AC_Avoidance/AC_Avoidance_config.h>

//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
// HARDWARE CONFIGURATION AND CONNECTIONS
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////

#ifndef CONFIG_HAL_BOARD
#error CONFIG_HAL_BOARD must be defined to build ArduCopter
#endif

#ifndef ARMING_DELAY_SEC
    # define ARMING_DELAY_SEC 2.0f
#endif


//////////////////////////////////////////////////////////////////////////////
// FRAME_CONFIG
//
#ifndef FRAME_CONFIG
 # define FRAME_CONFIG   MULTICOPTER_FRAME
#endif

/////////////////////////////////////////////////////////////////////////////////
// TradHeli defaults
#if FRAME_CONFIG == HELI_FRAME
  # define RC_FAST_SPEED                        125
  # define WP_YAW_BEHAVIOR_DEFAULT              WP_YAW_BEHAVIOR_LOOK_AHEAD
#endif

//////////////////////////////////////////////////////////////////////////////
// PWM control
// default RC speed in Hz
#ifndef RC_FAST_SPEED
   #   define RC_FAST_SPEED 490
#endif

//////////////////////////////////////////////////////////////////////////////
// Rangefinder
//

#ifndef RANGEFINDER_FILT_DEFAULT
 # define RANGEFINDER_FILT_DEFAULT 0.5f     // filter for rangefinder distance
#endif

#ifndef SURFACE_TRACKING_TIMEOUT_MS
 # define SURFACE_TRACKING_TIMEOUT_MS  1000 // surface tracking target alt will reset to current rangefinder alt after this many milliseconds without a good rangefinder alt
#endif

#ifndef MAV_SYSTEM_ID
 # define MAV_SYSTEM_ID          1
#endif

// prearm GPS hdop check
#ifndef GPS_HDOP_GOOD_DEFAULT
 # define GPS_HDOP_GOOD_DEFAULT         140     // minimum hdop that represents a good position.  used during pre-arm checks if fence is enabled
#endif

// missing terrain data failsafe
#ifndef FS_TERRAIN_TIMEOUT_MS
 #define FS_TERRAIN_TIMEOUT_MS          5000     // 5 seconds of missing terrain data will trigger failsafe (RTL)
#endif

// pre-arm baro vs inertial nav max alt disparity
#ifndef PREARM_MAX_ALT_DISPARITY_M
 # define PREARM_MAX_ALT_DISPARITY_M    1.0      // barometer and inertial nav altitude must be within this many meters
#endif

//////////////////////////////////////////////////////////////////////////////
//  EKF Failsafe
#ifndef FS_EKF_ACTION_DEFAULT
 # define FS_EKF_ACTION_DEFAULT         FS_EKF_ACTION_LAND  // EKF failsafe triggers land by default
#endif
#ifndef FS_EKF_THRESHOLD_DEFAULT
 # define FS_EKF_THRESHOLD_DEFAULT      0.8f    // EKF failsafe's default compass and velocity variance threshold above which the EKF failsafe will be triggered
#endif

#ifndef EKF_ORIGIN_MAX_ALT_KM
 # define EKF_ORIGIN_MAX_ALT_KM         50   // EKF origin and home must be within 50km vertically
#endif

#ifndef FS_EKF_FILT_DEFAULT
# define FS_EKF_FILT_DEFAULT     5.0f    // frequency cutoff of EKF variance filters
#endif

//////////////////////////////////////////////////////////////////////////////
//  Auto Tuning
#ifndef AUTOTUNE_ENABLED
 # define AUTOTUNE_ENABLED  1
#endif

//////////////////////////////////////////////////////////////////////////////
// Nav-Guided - allows external nav computer to control vehicle
#ifndef AC_NAV_GUIDED
 # define AC_NAV_GUIDED    1
#endif

//////////////////////////////////////////////////////////////////////////////
// Acro - fly vehicle in acrobatic mode
#ifndef MODE_ACRO_ENABLED
# define MODE_ACRO_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// Auto mode - allows vehicle to trace waypoints and perform automated actions
#ifndef MODE_AUTO_ENABLED
# define MODE_AUTO_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// Brake mode - bring vehicle to stop
#ifndef MODE_BRAKE_ENABLED
# define MODE_BRAKE_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// Circle - fly vehicle around a central point
#ifndef MODE_CIRCLE_ENABLED
# define MODE_CIRCLE_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// Drift - fly vehicle in altitude-held, coordinated-turn mode
#ifndef MODE_DRIFT_ENABLED
# define MODE_DRIFT_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// flip - fly vehicle in flip in pitch and roll direction mode
#ifndef MODE_FLIP_ENABLED
# define MODE_FLIP_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// Follow - follow another vehicle or GCS
#ifndef MODE_FOLLOW_ENABLED
#if AP_FOLLOW_ENABLED && AP_AVOIDANCE_ENABLED
#define MODE_FOLLOW_ENABLED 1
#else
#define MODE_FOLLOW_ENABLED 0
#endif
#endif


//////////////////////////////////////////////////////////////////////////////
// Rescue mode - control vehicle's position or angles from GCS
#ifndef MODE_RESCUE_ENABLED
# define MODE_RESCUE_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// Dynamic Landing mode - allows vehicle to perform dynamic landing maneuvers
#ifndef MODE_DYNAMIC_LANDING_ENABLED
# define MODE_DYNAMIC_LANDING_ENABLED 1
#endif

// //////////////////////////////////////////////////////////////////////////////
// // Custom Parameter - Detection threshold for Dynamic Land Mode
// #if MODE_RESCUE_ENABLED

// //Navigation Parameters
// #ifndef WP_THR_DEFAULT
//  # define WP_THR_DEFAULT                        3                   // in meters, threshold to consider that the drone has reached the waypoint
// #endif
// #ifndef WP_THR_END_DEFAULT
//     # define WP_THR_END_DEFAULT                 50                  // in meters, threshold to consider that the drone has reached the waypoint for endurance
// #endif
// #ifndef DYN_TAR_THR_DEFAULT
//  # define DYN_TAR_THR_DEFAULT                   4                   // in meters, threshold to consider that the drone has reached the dynamic target
// #endif
// #ifndef POS_MSG_SENT_RATE_DEFAULT
//  # define POS_MSG_SENT_RATE_DEFAULT             0.1f                // in seconds, rate at which position messages are sent to the drone
// #endif
// #ifndef VEL_MSG_SENT_RATE_DEFAULT
//  # define VEL_MSG_SENT_RATE_DEFAULT             0.033f              // in seconds, rate at which velocity messages are sent to the drone
// #endif
// #ifndef STP_ACC_DEFAULT
//  # define STP_ACC_DEFAULT                       1.2f                // in m/s^2, deceleration to apply when stopping the drone
// #endif
// #ifndef MAX_STOP_DIS_DEFAULT
//  # define MAX_STOP_DIS_DEFAULT                  15                  // in meters, max distance to create a hold point when the target is detected
// #endif
// #ifndef MISS_TIMOUT_DEFAULT
//  # define MISS_TIMEOUT_DEFAULT                 1200                 // in seconds, timeout for the entire mission
// #endif

// // Round About Parameters
// #ifndef INIT_ROUND_ABT_OR_DEFAULT
//  # define INIT_ROUND_ABT_OR_DEFAULT   "cw"    // 'cw' for clockwise, 'ccw' for counterclockwise, initial orientation for the round about maneuver
// #endif
// #ifndef ROUND_ABT_ORBIT_RAD_DEFAULT
//  # define ROUND_ABT_ORBIT_RAD_DEFAULT  30    // default radius of the round about orbit in m
// #endif
// #ifndef ROUND_ABT_ANG_SPD_DEG_DEFAULT
//  # define ROUND_ABT_ANG_SPD_DEG_DEFAULT 18    // default angular speed during the round about in deg/s
// #endif
// #ifndef ROUND_ABT_INIT_THR_DEFAULT
//  # define ROUND_ABT_INIT_THR_DEFAULT  100    // default throttle during the initial stage of the round about maneuver, as a fraction of maximum throttle
// #endif

// // Home Parameters
// #ifndef FLW_LKAHD_FAC_DEFAULT
//  # define FLW_LKAHD_FAC_DEFAULT       0.28    // default look-ahead factor for Follow mode in seconds, used to calculate the point ahead of the target that the vehicle should aim for
// #endif
// #ifndef FLW_TAR_ALT_DEFAULT
//  # define FLW_TAR_ALT_DEFAULT         9   // default altitude to fly at in Follow mode in m
// #endif

// // Landing Parameters
// #ifndef ALT_REST_CONE_FACTOR_DEFAULT
//  # define ALT_REST_CONE_FACTOR_DEFAULT 0.89    // default altitude restriction cone factor for landing in Follow mode, between 0 and 1, where 1 means no cone and 0 means the vehicle must be at or below the altitude of the target to be able to land
// #endif
// #ifndef MAR_TIME_THR_DEFAULT
//  # define MAR_TIME_THR_DEFAULT        5    // default time threshold for the minimum time to be below the altitude restriction cone for landing in Follow mode in seconds
// #endif
// #ifndef MAR_DET_THR_DEFAULT
//  # define MAR_DET_THR_DEFAULT         7    // default detection threshold for determining if the vehicle is below the altitude restriction cone for landing in Follow mode, between 0 and 1, where 1 means perfectly below the cone and 0 means perfectly above the cone
// #endif
// #ifndef MOT_CUTOFF_THR_DEFAULT
//  # define MOT_CUTOFF_THR_DEFAULT      0.5    // default throttle cutoff threshold for landing in Follow mode, as a fraction of maximum throttle
// #endif

// // Logging Parameters
// #ifndef LOG_INT_DEFAULT
//  # define LOG_INT_DEFAULT             0.05    // default logging interval in seconds for Follow mode
// #endif

// // Gimbal Parameters
// #ifndef GMB_MSG_SENT_RATE_DEFAULT
//  # define GMB_MSG_SENT_RATE_DEFAULT   0.05    // default rate at which gimbal control messages are sent in Hz
// #endif
// #ifndef GMB_HFOV_DEFAULT
//  # define GMB_HFOV_DEFAULT            84.5   // default horizontal field of view of the gimbal in degrees, used to calculate the gimbal control angles
// #endif
// #ifndef GMB_VFOV_DEFAULT
//  # define GMB_VFOV_DEFAULT            54.0   // default vertical field of view of the gimbal in degrees, used to calculate the gimbal control angles
// #endif
// #ifndef GMB_CAM_WID_DEFAULT
//  # define GMB_CAM_WID_DEFAULT         1280    // default width of the gimbal camera in pixels, used to calculate the gimbal control angles
// #endif
// #ifndef GMB_CAM_HGT_DEFAULT
//  # define GMB_CAM_HGT_DEFAULT         720     // default height of the gimbal camera in pixels, used to calculate the gimbal control angles
// #endif
// #ifndef GMB_CNTR_SMTH_FACT_DEFAULT
//  # define GMB_CNTR_SMTH_FACT_DEFAULT 0.1    // default smoothing factor for the gimbal control angles, between 0 and 1, where 0 means no smoothing and 1 means complete smoothing (i.e. the gimbal control angles will not change)
// #endif
// #ifndef GMB_PIT_POINT_DEFAULT
//  # define GMB_PIT_POI_POINT_DEFAULT   -70    // default point for the gimbal to aim at in the vertical direction, between 0 and 1, where 0 means the bottom of the camera view and 1 means the top of the camera view
// #endif
// #ifndef GMB_YAW_POINT_DEFAULT
//  # define GMB_YAW_POINT_DEFAULT       0    // default point for the gimbal to aim at in the horizontal direction, between 0 and 1, where 0 means the left of the camera view and 1 means the right of the camera view
// #endif
// #ifndef GMB_PIT_COR_DEFAULT
//  # define GMB_PIT_COR_DEFAULT         -60    // default correction angle for the gimbal in the vertical direction in degrees, used to correct for any misalignment of the gimbal in the vertical direction
// #endif
// #ifndef GMB_YAW_COR_DEFAULT
//  # define GMB_YAW_COR_DEFAULT         30    // default correction angle for the gimbal in the horizontal direction in degrees, used to correct for any misalignment of the gimbal in the horizontal direction
// #endif

// // Detection Parameters
// #ifndef DET_CNF_THR_DEFAULT
//  # define DET_CNF_THR_DEFAULT         0.9     // default detection threshold for Follow mode in seconds, used to determine if the target is detected or not
// #endif
// #ifndef CLS_NAMES_DEFAULT
//  # define CLS_NAMES_DEFAULT           ["person"]    // default class names for detection in Follow mode, used to determine if the detected target is the correct type or not
// #endif
// #ifndef DET_WIN_DUR_DEFAULT
//  # define DET_WIN_DUR_DEFAULT         3     // default duration of the detection window in seconds, used to determine if the target is detected or not
// #endif
// #ifndef MIN_DET_TRACK_DEFAULT
//  # define MIN_DET_TRACK_DEFAULT       10    // default minimum number of detections in the detection window required to consider the target detected
// #endif
// #ifndef MIN_DET_TRACK_INT_DEFAULT
//  # define MIN_DET_TRACK_INT_DEFAULT   5    // default minimum number of detections in the detection window required to consider the target detected
// #endif
// #ifndef TRACK_TIMEOUT_DEFAULT
//  # define TRACK_TIMEOUT_DEFAULT        5     // default time in seconds without detections before the target is considered lost
// #endif

// //Sensor Parameters
// #ifndef RAD_MSG_ID_DEFAULT
//  # define RAD_MSG_ID_DEFAULT          1     // default MAVLink message ID for the target's rangefinder distance, used to determine if the target is detected or not
// #endif
// #ifndef LID_MSG_ID_DEFAULT
//  # define LID_MSG_ID_DEFAULT          0     // default MAVLink message ID for the target's lidar distance, used to determine if the target is detected or not
// #endif
// #ifndef LIFE_PWM_CH_DEFAULT
//  # define LIFE_PWM_CH_DEFAULT         [9, 10, 11]     // default RC channel for the target's heartbeat signal, used to determine if the target is detected or not
// #endif
// #ifndef LIFE_PWM_VAL_DEFAULT
//  # define LIFE_PWM_VAL_DEFAULT        [1800, 1800, 1700]    // default RC channel value for the target's heartbeat signal, used to determine if the target is detected or not
// #endif
// #ifndef LIFE+DEP_ALT_DEFAULT
//  # define LIFE_DEP_ALT_DEFAULT        15    // default altitude in m above the target at which to maintain in Follow mode
// #endif

// #endif

//////////////////////////////////////////////////////////////////////////////
// Guided mode - control vehicle's position or angles from GCS
#ifndef MODE_GUIDED_ENABLED
# define MODE_GUIDED_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// GuidedNoGPS mode - control vehicle's angles from GCS
#ifndef MODE_GUIDED_NOGPS_ENABLED
# define MODE_GUIDED_NOGPS_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// Loiter mode - allows vehicle to hold global position
#ifndef MODE_LOITER_ENABLED
# define MODE_LOITER_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// Position Hold - enable holding of global position
#ifndef MODE_POSHOLD_ENABLED
# define MODE_POSHOLD_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// RTL - Return To Launch
#ifndef MODE_RTL_ENABLED
# define MODE_RTL_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// SmartRTL - allows vehicle to retrace a (loop-eliminated) breadcrumb home
#ifndef MODE_SMARTRTL_ENABLED
# define MODE_SMARTRTL_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// Sport - fly vehicle in rate-controlled (earth-frame) mode
#ifndef MODE_SPORT_ENABLED
# define MODE_SPORT_ENABLED 0
#endif

//////////////////////////////////////////////////////////////////////////////
// System ID - conduct system identification tests on vehicle
#ifndef MODE_SYSTEMID_ENABLED
# define MODE_SYSTEMID_ENABLED HAL_LOGGING_ENABLED
#endif

//////////////////////////////////////////////////////////////////////////////
// Throw - fly vehicle after throwing it in the air
#ifndef MODE_THROW_ENABLED
# define MODE_THROW_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// ZigZag - allow vehicle to fly in a zigzag manner with predefined point A B
#ifndef MODE_ZIGZAG_ENABLED
# define MODE_ZIGZAG_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////
// Turtle - allow vehicle to be flipped over after a crash
#ifndef MODE_TURTLE_ENABLED
# define MODE_TURTLE_ENABLED HAL_DSHOT_ENABLED && FRAME_CONFIG != HELI_FRAME
#endif

//////////////////////////////////////////////////////////////////////////////
// Flowhold - use optical flow to hover in place
#ifndef MODE_FLOWHOLD_ENABLED
# define MODE_FLOWHOLD_ENABLED AP_OPTICALFLOW_ENABLED
#endif

//////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////
// Weathervane - allow vehicle to yaw into wind
#ifndef WEATHERVANE_ENABLED
# define WEATHERVANE_ENABLED 1
#endif

//////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////
// Autorotate - autonomous auto-rotation - helicopters only
#ifndef MODE_AUTOROTATE_ENABLED
#if CONFIG_HAL_BOARD == HAL_BOARD_SITL
    #if FRAME_CONFIG == HELI_FRAME
        #ifndef MODE_AUTOROTATE_ENABLED
        # define MODE_AUTOROTATE_ENABLED 1
        #endif
    #else
        # define MODE_AUTOROTATE_ENABLED 0
    #endif
#else
    # define MODE_AUTOROTATE_ENABLED 0
#endif
#endif

//////////////////////////////////////////////////////////////////////////////
// RADIO CONFIGURATION
//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
// FLIGHT_MODE
//

#ifndef FLIGHT_MODE_1
 # define FLIGHT_MODE_1                  Mode::Number::STABILIZE
#endif
#ifndef FLIGHT_MODE_2
 # define FLIGHT_MODE_2                  Mode::Number::STABILIZE
#endif
#ifndef FLIGHT_MODE_3
 # define FLIGHT_MODE_3                  Mode::Number::STABILIZE
#endif
#ifndef FLIGHT_MODE_4
 # define FLIGHT_MODE_4                  Mode::Number::STABILIZE
#endif
#ifndef FLIGHT_MODE_5
 # define FLIGHT_MODE_5                  Mode::Number::STABILIZE
#endif
#ifndef FLIGHT_MODE_6
 # define FLIGHT_MODE_6                  Mode::Number::STABILIZE
#endif

#ifndef FLIGHT_MODE_7
 # define FLIGHT_MODE_7                  Mode::Number::STABILIZE
#endif
#ifndef FLIGHT_MODE_8
 # define FLIGHT_MODE_8                  Mode::Number::STABILIZE
#endif


//////////////////////////////////////////////////////////////////////////////
// Throttle Failsafe
//
#ifndef FS_THR_VALUE_DEFAULT
 # define FS_THR_VALUE_DEFAULT             975
#endif

//////////////////////////////////////////////////////////////////////////////
// Takeoff
//
#ifndef PILOT_TKOFF_ALT_DEFAULT
 # define PILOT_TKOFF_ALT_DEFAULT           0     // default final alt above home for pilot initiated takeoff
#endif


//////////////////////////////////////////////////////////////////////////////
// Landing
//
#ifndef LAND_SPEED
 # define LAND_SPEED    50          // the descent speed for the final stage of landing in cm/s
#endif
#ifndef LAND_REPOSITION_DEFAULT
 # define LAND_REPOSITION_DEFAULT   1   // by default the pilot can override roll/pitch during landing
#endif
#ifndef LAND_WITH_DELAY_MS
 # define LAND_WITH_DELAY_MS        4000    // default delay (in milliseconds) when a land-with-delay is triggered during a failsafe event
#endif
#ifndef LAND_CANCEL_TRIGGER_THR
 # define LAND_CANCEL_TRIGGER_THR   700     // land is cancelled by input throttle above 700
#endif
#ifndef LAND_RANGEFINDER_MIN_ALT_M
#define LAND_RANGEFINDER_MIN_ALT_M  2.0
#endif

//////////////////////////////////////////////////////////////////////////////
// Landing Detector
//
#ifndef LAND_DETECTOR_TRIGGER_SEC
 # define LAND_DETECTOR_TRIGGER_SEC         1.0f    // number of seconds to detect a landing
#endif
#ifndef LAND_AIRMODE_DETECTOR_TRIGGER_SEC
 # define LAND_AIRMODE_DETECTOR_TRIGGER_SEC 3.0f    // number of seconds to detect a landing in air mode
#endif
#ifndef LAND_DETECTOR_MAYBE_TRIGGER_SEC
 # define LAND_DETECTOR_MAYBE_TRIGGER_SEC   0.2f    // number of seconds that means we might be landed (used to reset horizontal position targets to prevent tipping over)
#endif
#ifndef LAND_DETECTOR_ACCEL_LPF_CUTOFF
# define LAND_DETECTOR_ACCEL_LPF_CUTOFF     1.0f    // frequency cutoff of land detector accelerometer filter
#endif
#ifndef LAND_DETECTOR_ACCEL_MAX
# define LAND_DETECTOR_ACCEL_MAX            1.0f    // vehicle acceleration must be under 1m/s/s
#endif
#ifndef LAND_DETECTOR_VEL_Z_MAX
# define LAND_DETECTOR_VEL_Z_MAX              1.0f    // vehicle vertical velocity must be under 1m/s
#endif

//////////////////////////////////////////////////////////////////////////////
// Flight mode definitions
//

// Acro Mode
#ifndef ACRO_LEVEL_MAX_ANGLE_RAD
 # define ACRO_LEVEL_MAX_ANGLE_RAD      radians(30.0)   // maximum lean angle in trainer mode measured in radians
#endif

#ifdef ACRO_LEVEL_MAX_ANGLE
#error "Please update your hwdef to use ACRO_LEVEL_MAX_ANGLE_RAD, not ACRO_LEVEL_MAX_ANGLE"
#endif // ACRO_LEVEL_MAX_ANGLE

#ifndef ACRO_LEVEL_MAX_OVERSHOOT_RAD
 # define ACRO_LEVEL_MAX_OVERSHOOT_RAD  radians(10.0) // maximum overshoot angle in trainer mode when full roll or pitch stick is held in radians
#endif

#ifdef ACRO_LEVEL_MAX_OVERSHOOT
#error "Please update your hwdef to use ACRO_LEVEL_MAX_OVERSHOOT_RAD, not ACRO_LEVEL_MAX_OVERSHOOT"
#endif // ACRO_LEVEL_MAX_OVERSHOOT

#ifndef ACRO_BALANCE_ROLL
 #define ACRO_BALANCE_ROLL          1.0f
#endif

#ifndef ACRO_BALANCE_PITCH
 #define ACRO_BALANCE_PITCH         1.0f
#endif

#ifndef ACRO_RP_EXPO_DEFAULT
 #define ACRO_RP_EXPO_DEFAULT       0.3f    // ACRO roll and pitch expo parameter default
#endif

#ifndef ACRO_Y_EXPO_DEFAULT
 #define ACRO_Y_EXPO_DEFAULT        0.0f    // ACRO yaw expo parameter default
#endif

#ifndef ACRO_THR_MID_DEFAULT
 #define ACRO_THR_MID_DEFAULT       0.0f
#endif

#ifndef ACRO_RP_RATE_DEFAULT
 #define ACRO_RP_RATE_DEFAULT      360      // ACRO roll and pitch rotation rate parameter default in deg/s
#endif

#ifndef ACRO_Y_RATE_DEFAULT
 #define ACRO_Y_RATE_DEFAULT       202.5    // ACRO yaw rotation rate parameter default in deg/s
#endif

// RTL Mode
#ifndef RTL_ALT_FINAL
 # define RTL_ALT_FINAL             0       // the altitude, in cm, the vehicle will move to as the final stage of Returning to Launch.  Set to zero to land.
#endif

#ifndef RTL_ALT
 # define RTL_ALT                   1500    // default alt to return to home in cm, 0 = Maintain current altitude
#endif

#ifndef RTL_ALT_MIN_M
 # define RTL_ALT_MIN_M             0.30     // min height above ground for RTL (i.e 0.3 m)
#endif

#ifndef RTL_CLIMB_MIN_DEFAULT
 # define RTL_CLIMB_MIN_DEFAULT     0       // vehicle will always climb this many cm as first stage of RTL
#endif

#ifndef RTL_CONE_SLOPE_DEFAULT
 # define RTL_CONE_SLOPE_DEFAULT    3.0f    // slope of RTL cone (height / distance). 0 = No cone
#endif

#ifndef RTL_MIN_CONE_SLOPE
 # define RTL_MIN_CONE_SLOPE        0.5f    // minimum slope of cone
#endif

#ifndef RTL_LOITER_TIME
 # define RTL_LOITER_TIME           5000    // Time (in milliseconds) to loiter above home before beginning final descent
#endif

// AUTO Mode
#ifndef WP_YAW_BEHAVIOR_DEFAULT
 # define WP_YAW_BEHAVIOR_DEFAULT   WP_YAW_BEHAVIOR_LOOK_AT_NEXT_WP_EXCEPT_RTL
#endif

#ifndef YAW_LOOK_AHEAD_MIN_SPEED_MS
 # define YAW_LOOK_AHEAD_MIN_SPEED_MS 1     // minimum ground speed in m/s required before copter is aimed at ground course
#endif

// Super Simple mode
#ifndef SUPER_SIMPLE_RADIUS_M
 # define SUPER_SIMPLE_RADIUS_M       10.0
#endif

//////////////////////////////////////////////////////////////////////////////
// Stabilize Rate Control
//
#ifndef ROLL_PITCH_YAW_INPUT_MAX
 # define ROLL_PITCH_YAW_INPUT_MAX      4500        // roll, pitch and yaw input range
#endif
#ifndef DEFAULT_ANGLE_MAX
 # define DEFAULT_ANGLE_MAX         3000            // ANGLE_MAX parameters default value
#endif

//////////////////////////////////////////////////////////////////////////////
// Stop mode defaults
//
#ifndef BRAKE_MODE_SPEED_Z_MS
 # define BRAKE_MODE_SPEED_Z_MS       2.50 // z-axis speed in m/s in Brake Mode
#endif
#ifndef BRAKE_MODE_DECEL_RATE_MSS
 # define BRAKE_MODE_DECEL_RATE_MSS   7.50 // acceleration rate in m/s/s in Brake Mode
#endif

//////////////////////////////////////////////////////////////////////////////
// PosHold parameter defaults
//
#ifndef POSHOLD_BRAKE_RATE_DEFAULT
 # define POSHOLD_BRAKE_RATE_DEFAULT    8       // default POSHOLD_BRAKE_RATE param value.  Rotation rate during braking in deg/sec
 # define POSHOLD_BRAKE_RATE_MIN        4       // default POSHOLD_BRAKE_RATE param value.  Rotation rate during braking in deg/sec
#endif
#ifndef POSHOLD_BRAKE_ANGLE_DEFAULT
 # define POSHOLD_BRAKE_ANGLE_DEFAULT   3000    // default POSHOLD_BRAKE_ANGLE param value.  Max lean angle during braking in centi-degrees
#endif

//////////////////////////////////////////////////////////////////////////////
// Pilot control defaults
//

#ifndef THR_DZ_DEFAULT
# define THR_DZ_DEFAULT         100             // the deadzone above and below mid throttle while in althold or loiter
#endif

// default maximum vertical velocity and acceleration the pilot may request
#ifndef PILOT_VELZ_MAX
 # define PILOT_VELZ_MAX    250     // maximum vertical velocity in cm/s
#endif
#ifndef PILOT_ACCEL_Z_DEFAULT
 # define PILOT_ACCEL_Z_DEFAULT 250 // vertical acceleration in cm/s/s while altitude is under pilot control
#endif

#ifndef PILOT_Y_RATE_DEFAULT
 # define PILOT_Y_RATE_DEFAULT  202.5   // yaw rotation rate parameter default in deg/s for all mode except ACRO
#endif
#ifndef PILOT_Y_EXPO_DEFAULT
 # define PILOT_Y_EXPO_DEFAULT  0.0     // yaw expo parameter default for all mode except ACRO
#endif

#ifndef AUTO_DISARMING_DELAY
# define AUTO_DISARMING_DELAY  10
#endif

//////////////////////////////////////////////////////////////////////////////
// Throw mode configuration
//
#ifndef THROW_HIGH_SPEED_MS
# define THROW_HIGH_SPEED_MS      5.0   // vehicle much reach this total 3D speed in cm/s (or be free falling)
#endif
#ifndef THROW_VERTICAL_SPEED_MS
# define THROW_VERTICAL_SPEED_MS  0.5   // motors start when vehicle reaches this total 3D speed in cm/s
#endif

//////////////////////////////////////////////////////////////////////////////
// Logging control
//

// Default logging bitmask
#ifndef DEFAULT_LOG_BITMASK
 # define DEFAULT_LOG_BITMASK \
    MASK_LOG_ATTITUDE_MED | \
    MASK_LOG_GPS | \
    MASK_LOG_PM | \
    MASK_LOG_CTUN | \
    MASK_LOG_NTUN | \
    MASK_LOG_RCIN | \
    MASK_LOG_IMU | \
    MASK_LOG_CMD | \
    MASK_LOG_CURRENT | \
    MASK_LOG_RCOUT | \
    MASK_LOG_OPTFLOW | \
    MASK_LOG_PID | \
    MASK_LOG_COMPASS | \
    MASK_LOG_CAMERA | \
    MASK_LOG_MOTBATT
#endif

//////////////////////////////////////////////////////////////////////////////
// Fence, Rally and Terrain and AC_Avoidance defaults
//

#if MODE_FOLLOW_ENABLED && !AP_AVOIDANCE_ENABLED
  #error Follow Mode relies on AP_AVOIDANCE_ENABLED which is disabled
#endif

#if MODE_AUTO_ENABLED && !MODE_GUIDED_ENABLED
  #error ModeAuto requires ModeGuided which is disabled
#endif

#if MODE_AUTO_ENABLED && !MODE_CIRCLE_ENABLED
  #error ModeAuto requires ModeCircle which is disabled
#endif

#if MODE_AUTO_ENABLED && !MODE_RTL_ENABLED
  #error ModeAuto requires ModeRTL which is disabled
#endif

#if FRAME_CONFIG == HELI_FRAME && !MODE_ACRO_ENABLED
  #error Helicopter frame requires acro mode support which is disabled
#endif

#if MODE_SMARTRTL_ENABLED && !MODE_RTL_ENABLED
  #error SmartRTL requires ModeRTL which is disabled
#endif

#if HAL_ADSB_ENABLED && !MODE_GUIDED_ENABLED
  #error ADSB requires ModeGuided which is disabled
#endif

#if MODE_FOLLOW_ENABLED && !MODE_GUIDED_ENABLED
  #error Follow requires ModeGuided which is disabled
#endif

#if MODE_GUIDED_NOGPS_ENABLED && !MODE_GUIDED_ENABLED
  #error ModeGuided-NoGPS requires ModeGuided which is disabled
#endif

//////////////////////////////////////////////////////////////////////////////
// Developer Items
//

#ifndef AP_COPTER_ADVANCED_FAILSAFE_ENABLED
# define AP_COPTER_ADVANCED_FAILSAFE_ENABLED 0
#endif

#ifndef AP_COPTER_AHRS_AUTO_TRIM_ENABLED
# define AP_COPTER_AHRS_AUTO_TRIM_ENABLED 1
#endif

#ifndef CH_MODE_DEFAULT
 # define CH_MODE_DEFAULT   5
#endif

#ifndef TOY_MODE_ENABLED
#define TOY_MODE_ENABLED 0
#endif

#if TOY_MODE_ENABLED && FRAME_CONFIG == HELI_FRAME
  #error Toy mode is not available on Helicopters
#endif

#ifndef HAL_FRAME_TYPE_DEFAULT
#define HAL_FRAME_TYPE_DEFAULT AP_Motors::MOTOR_FRAME_TYPE_X
#endif

#ifndef AC_CUSTOMCONTROL_MULTI_ENABLED
#define AC_CUSTOMCONTROL_MULTI_ENABLED FRAME_CONFIG == MULTICOPTER_FRAME && AP_CUSTOMCONTROL_ENABLED
#endif

#ifndef AC_PAYLOAD_PLACE_ENABLED
#define AC_PAYLOAD_PLACE_ENABLED 1
#endif

#ifndef USER_PARAMS_ENABLED
  #define USER_PARAMS_ENABLED 0
#endif
